# example.toml
# login information
[credentials]
  username = "<username>" #not required, can be entered using the credentials argument
  password = "<password>"#not required, can be entered using the credentials argument
  api_url = "<api_url>" #not required, can be entered using the credentials argument

# new log information
[main_log_info]
  title = "Destination Reached"
  description = "The beam has reached a new destination."
  level = "info"
  logbook = "tests"
  #check_time = 3 #not required. Waiting time for the loop to check pv value, default value: 5s

# pv information
[[autolog]]
  [autolog.context]
    description = "The destination is:"
    #attachment_file = "path/to/file/file.plt"
    [autolog.context.pv]
      info_pv_name = "SL-APP-MCS:BOM-CPU:BeamDestCodeTextIn"
      info_pv_desc = true
      as_string = 'yes'
  
  [autolog.trigger]
    trigger_pv_name = "SL-APP-MCS:BOM-CPU:BeamDestCode"
    trigger_pv_value = [1,2,3,4] #list of integer

  [autolog.condition]
    logical_condition = 'or'
    [[autolog.condition.pv]]
      condition_pv_name = "SL-APP-MCS:BOM-CPU:StartBeamCmd"
      condition_pv_value = [0] #list of integer

    [[autolog.condition.pv]]
      condition_pv_name = "SL-APP-MCS:BOM-CPU:StartBeamCmd"
      condition_pv_value = [1] #list of integer

[[autolog]]
  [autolog.context]
    description = "The destination is (second):"
    #attachment_file = "path/to/file/file.plt"
    [autolog.context.pv]
      info_pv_name = "SL-APP-MCS:BOM-CPU:BeamDestCodeTextIn"
      info_pv_desc = true
      as_string = 'only'

  [autolog.trigger]
    trigger_pv_name = "SL-APP-MCS:BOM-CPU:BeamDestCode"
    trigger_pv_value = [1,2,3,4] #list of integer
  

  [autolog.condition]
    logical_condition = 'and'
    [[autolog.condition.pv]]
      condition_pv_name = "SL-APP-MCS:BOM-CPU:StartBeamCmd"
      condition_pv_value = [1] #list of integer

    [[autolog.condition.pv]]
      condition_pv_name = "SL-APP-MCS:BOM-CPU:StartBeamCmd"
      condition_pv_value = [1] #list of integer
